# This is the default/common configuration applied to all profiles
spring:
  profiles:
    # This now acts as the default profile to use when you run the app
    active: db

server:
  port: 8080

--- # The triple-dash separator indicates the start of a new, profile-specific configuration

# --- DATABASE ('db') PROFILE CONFIGURATION ---
spring:
  config:
    activate:
      on-profile: "db" # These settings are ONLY active when the 'db' profile is used
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=alexauto;trustServerCertificate=true
    username: sa
    password: Password123#
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

---

# --- IN-MEMORY ('json') PROFILE CONFIGURATION ---
spring:
  config:
    activate:
      on-profile: "json" # These settings are ONLY active when the 'json' profile is used
  autoconfigure:
    exclude: # This exclusion now correctly applies ONLY to the json profile
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration